#!/bin/sh
# Set DISTRUBUTION_LOG_NOTFOUND=1 to log 'not founded' command in /tmp/not_found.txt
# Build: %%DATE%%
pgm="${0##*/}"		# Program basename
progdir="${0%/*}"	# Program directory

jailed=$( /sbin/sysctl -qn security.jail.jailed )

if [ ${jailed} -eq 1 ]; then
	# is RW?
	touch /bin/distribution > /dev/null 2>&1
	_ret=$?
	if [ ${_ret} -eq 0 ]; then
		# probably baserw=1/writable jail, reset jailed
		jailed=0
	fi
fi
