#!/bin/sh
# Set DISTRUBUTION_LOG_NOTFOUND=1 to log 'not founded' command in /tmp/not_found.txt
# Build: %%DATE%%
pgm="${0##*/}"		# Program basename
progdir="${0%/*}"	# Program directory

# recursion?
[ -n "${CBSD_DISTRIBUTION_HELPER}" ] && exit 0
export CBSD_DISTRIBUTION_HELPER=1

if [ -x /sbin/sysctl ]; then
	jailed=$( /sbin/sysctl -qn security.jail.jailed )
else
	jailed=1	# limited env?
fi

if [ ${jailed} -eq 1 ]; then
	# is RW?
	if [ -x /usr/bin/touch ]; then
		/usr/bin/touch /bin/distribution > /dev/null 2>&1
		_ret=$?
	else
		jailed=0		# unknown state
	fi
	if [ ${_ret} -eq 0 ]; then
		# probably baserw=1/writable jail, reset jailed
		jailed=0
	fi
fi
