#!/bin/sh
# Set DISTRUBUTION_LOG_NOTFOUND=1 to log 'not founded' command in /tmp/not_found.txt
# Build: %%DATE%%
pgm="${0##*/}"		# Program basename
progdir="${0%/*}"	# Program directory

jailed=$( /sbin/sysctl -qn security.jail.jailed )
